name: Build and Release

on:
    push:
        tags:
            - "v*"

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm install

            - name: Install rcedit
              run: npm install -g rcedit

            - name: Build .exe
              run: npx pkg client.js --targets node18-win-x64 --output dist/SecureChat.exe --icon icon.ico

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/SecureChat.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
