name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm install

            - name: Install rcedit
              run: npm install -g rcedit

            - name: Build .exe
              run: npx pkg client.js --targets node18-win-x64 --output dist/SecureChat.exe --icon icon.ico

            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release create ${{ github.ref_name }} dist/SecureChat.exe --generate-notes || gh release upload ${{ github.ref_name }} dist/SecureChat.exe
